#!/bin/bash

cd /tmp

# Create the conf file for root to specify the soft stack limit.
#
# When running in docker - we start sqlserver as root.
# Also set the same limit for user 'mssql' if we decide
# to run as that user in the future.
#
# This is done to ensure that the sqlservr (started under user mssql)
# doesn't  fallback to a legacy VA layout and place mmap_base at ~42TB.
#
echo "root soft stack 8192" > /etc/security/limits.d/99-mssql-server.conf
echo "mssql soft stack 8192" >> /etc/security/limits.d/99-mssql-server.conf

# Install required packages
#
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get -y upgrade
apt-get -y install libunwind8 libnuma1 libjemalloc1 libc++1 gdb libssl1.0.0 openssl python python3 libgssapi-krb5-2 libsss-nss-idmap0 wget apt-transport-https locales gawk sed lsof pbzip2 libldap-2.4-2 libsasl2-2 libsasl2-modules-gssapi-mit

# Configure UTF-8 locale
#
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
locale-gen

# Install packages.microsoft.com repository configuration
#
wget http://packages.microsoft.com/ubuntu/16.04/prod/pool/main/p/packages-microsoft-prod/packages-microsoft-prod_1.0-1-xenial.deb
dpkg -i packages-microsoft-prod_1.0-1-xenial.deb

# Install mssql-tools package
#
apt-get update
ACCEPT_EULA=Y apt-get -y --no-install-recommends install mssql-tools

# Remove files from /tmp
#
rm -rf /tmp/*

# Remove files from apt cache
#
apt-get clean
rm -rf /var/lib/apt/lists/*
